In [ ]:
!python --version

Python 3.12.12


In [ ]:
!git clone https://github.com/facebookresearch/ImageBind.git

fatal: destination path 'ImageBind' already exists and is not an empty directory.


In [ ]:
%cd ./ImageBind

/content/ImageBind


In [ ]:
# Install PyTorch with TPU support
!pip install torch~=2.3 torch_xla[tpu] -f https://storage.googleapis.com/libtpu-releases/index.html

Looking in links: https://storage.googleapis.com/libtpu-releases/index.html


In [ ]:
!pip install .

Processing /content/ImageBind
  Preparing metadata (setup.py) ... done
  Using cached pytorchvideo-0.1.5-py3-none-any.whl
  Created wheel for imagebind: filename=imagebind-0.1.0-py3-none-any.whl size=1385592 sha256=4c23b9aa388b3246637e25c987b0b29387835c1ac30d0223dd6a74f62b0f9b5a
  Stored in directory: /tmp/pip-ephem-wheel-cache-i7kfi8ck/wheels/09/6b/b8/2f3b0adfbc0a97c03fd8d07f41806ebae57d614fffbf48c13e
Successfully built imagebind
  Attempting uninstall: imagebind
    Found existing installation: imagebind 0.1.0
    Uninstalling imagebind-0.1.0:
      Successfully uninstalled imagebind-0.1.0


In [ ]:
!pip install decord

In [ ]:
!ls

build		    imagebind		model_card.md	  setup.py
CODE_OF_CONDUCT.md  imagebind.egg-info	README.md
CONTRIBUTING.md     LICENSE		requirements.txt


In [ ]:
# Verify PyTorch and TPU installation
# import torch
# import torch_xla.core.xla_model as xm

# print(f"PyTorch version: {torch.__version__}")
# print(f"TPU device: {xm.xla_device()}")

ImportError: /usr/local/lib/python3.12/dist-packages/_XLAC.cpython-312-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda10set_deviceEa

In [ ]:
# Using wget to download from Google Drive (append &export=download to the URL)
# !wget -q --show-progress "https://drive.google.com/file/d/1DDj8l59RyEoE2zeeYAqfg9wHiiZehUfg/view?usp=drive_link&export=download"   -O dataset.zip
!wget -q --show-progress "https://docs.google.com/uc?export=download&id=1DDj8l59RyEoE2zeeYAqfg9wHiiZehUfg" -O dataset.zip


dataset.zip         100%[===================>]   2.36K  --.-KB/s    in 0s      


In [ ]:
# In a Colab cell

FILE_ID="1DDj8l59RyEoE2zeeYAqfg9wHiiZehUfg"
OUT="dataset.zip"

# Step 1: fetch the confirm token while saving cookies
!(confirm=$(wget -q --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate \
  "https://docs.google.com/uc?export=download&id=${FILE_ID}" -O- | \
  sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1/p'))

# Step 2: download with the token and cookies
!(wget -q --show-progress --load-cookies /tmp/cookies.txt \
  "https://docs.google.com/uc?export=download&confirm=${confirm}&id=${FILE_ID}" \
  -O "${OUT}")

No such file or directory


In [ ]:
!cp ../drive/MyDrive/ads-copy.zip ./

In [ ]:
!unzip ads-copy.zip

Archive:  ads-copy.zip
   creating: ads/
  inflating: ads/.DS_Store           
  inflating: __MACOSX/ads/._.DS_Store  
   creating: ads/images/
   creating: ads/videos/
  inflating: ads/images/i0018.png    
  inflating: __MACOSX/ads/images/._i0018.png  
  inflating: ads/images/i0009.png    
  inflating: __MACOSX/ads/images/._i0009.png  
  inflating: ads/images/i0008.png    
  inflating: __MACOSX/ads/images/._i0008.png  
  inflating: ads/images/i0006.png    
  inflating: __MACOSX/ads/images/._i0006.png  
  inflating: ads/images/i0012.png    
  inflating: __MACOSX/ads/images/._i0012.png  
  inflating: ads/images/i0013.png    
  inflating: __MACOSX/ads/images/._i0013.png  
  inflating: ads/images/i0007.png    
  inflating: __MACOSX/ads/images/._i0007.png  
  inflating: ads/images/i0011.png    
  inflating: __MACOSX/ads/images/._i0011.png  
  inflating: ads/images/i0005.png    
  inflating: __MACOSX/ads/images/._i0005.png  
  inflating: ads/images/i0004.png    
  inflating: __MACOSX/ads/im

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import os

def list_files_in_directory(directory_path):
  """
  Lists all files in a given directory.

  Args:
    directory_path: The path to the directory.

  Returns:
    A list of file paths within the directory.
  """
  file_list = []
  for filename in os.listdir(directory_path):
    file_path = os.path.join(directory_path, filename)
    if os.path.isfile(file_path):
      file_list.append(file_path)
  return file_list

# Example usage:
video_path = list_files_in_directory('./ads/videos')
image_path = list_files_in_directory('./ads/images')

# print(my_files)

In [ ]:
print(image_path)
print(video_path)

['./ads/images/i0006.png', './ads/images/i0017.png', './ads/images/i0004.png', './ads/images/i0015.png', './ads/images/i0018.png', './ads/images/i0002.png', './ads/images/i0012.png', './ads/images/i0016.png', './ads/images/i0014.png', './ads/images/i0001.png', './ads/images/i0009.png', './ads/images/i0003.png', './ads/images/i0011.png', './ads/images/i0010.png', './ads/images/i0008.png', './ads/images/i0005.png', './ads/images/i0013.png', './ads/images/i0007.png']
['./ads/videos/v0007.mp4', './ads/videos/v0022.mp4', './ads/videos/v0002.mp4', './ads/videos/v0011.mp4', './ads/videos/v0019.mp4', './ads/videos/v0016.mp4', './ads/videos/v0014.mp4', './ads/videos/v0001.mp4', './ads/videos/v0003.mp4', './ads/videos/v0012.mp4', './ads/videos/v0009.mp4', './ads/videos/v0005.mp4', './ads/videos/v0013.mp4', './ads/videos/v0021.mp4', './ads/videos/v0010.mp4', './ads/videos/v0004.mp4', './ads/videos/v0017.mp4', './ads/videos/v0023.mp4', './ads/videos/v0015.mp4', './ads/videos/v0020.mp4', './ads/vid

In [ ]:
import torch

if torch.cuda.is_available():
    print("CUDA is available. Using GPU.")
else:
    print("CUDA is not available. Using CPU.")

CUDA is available. Using GPU.


In [ ]:
!ls /content/

build  decord  drive  ImageBind  sample_data


In [ ]:
%cd /content/ImageBind/

/content/ImageBind


In [ ]:
from imagebind import data
import torch
from imagebind.models import imagebind_model
from imagebind.models.imagebind_model import ModalityType
# import torch_xla
# import torch_xla.core.xla_model as xm

# text_list=["A dog.", "A car", "A bird"]
# image_paths=[".assets/dog_image.jpg", ".assets/car_image.jpg", ".assets/bird_image.jpg"]
# audio_paths=[".assets/dog_audio.wav", ".assets/car_audio.wav", ".assets/bird_audio.wav"]

# image_paths=[".assets/dog_image.jpg", ".assets/car_image.jpg", ".assets/bird_image.jpg"]


# device = xm.xla_device()
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Instantiate model
model = imagebind_model.imagebind_huge(pretrained=True)
model.eval()
model.to(device)

# Load data
# inputs = {
#     ModalityType.TEXT: data.load_and_transform_text(text_list, device),
#     ModalityType.VISION: data.load_and_transform_vision_data(image_paths, device),

#     ModalityType.AUDIO: data.load_and_transform_audio_data(audio_paths, device),
# }

inputs_vid = {
    ModalityType.VISION: data.load_and_transform_video_data(video_path, device)
}

inputs_img = {
    ModalityType.VISION: data.load_and_transform_vision_data(image_path, device)
}

with torch.no_grad():
    emb_img = model(inputs_img)
    emb_vid = model(inputs_vid)

# print(
#     "Vision x Text: ",
#     torch.softmax(embeddings[ModalityType.VISION] @ embeddings[ModalityType.TEXT].T, dim=-1),
# )
# print(
#     "Audio x Text: ",
#     torch.softmax(embeddings[ModalityType.AUDIO] @ embeddings[ModalityType.TEXT].T, dim=-1),
# )
# print(
#     "Vision x Audio: ",
#     torch.softmax(embeddings[ModalityType.VISION] @ embeddings[ModalityType.AUDIO].T, dim=-1),
print(
    "Similarity comparison matrix: ",
    torch.softmax(emb_img[ModalityType.VISION] @ emb_vid[ModalityType.VISION].T, dim=-1),
)


In [ ]:
%cd /content/ImageBind

/content/ImageBind


In [ ]:
!mv ../imagebind_index_search.py ./

In [ ]:
!mv ../imagebind_index_searchv2.py ./

In [ ]:
!python imagebind_index_searchv2.py index \
  --images ./ads/images/ \
  --videos ./ads/videos/ \
  --out-dir ./out_dataset/ \
  --image-batch 16 \
  --clips-per-video 1 \
  --clip-duration-frames 2 \
  --resume


Traceback (most recent call last):
  File "/content/ImageBind/imagebind_index_searchv2.py", line 245, in <module>
    for p in tqdm(vid_paths, desc="Videos"):
                  ^^^^^^^^^
NameError: name 'vid_paths' is not defined


## Installing Decord with GPU support

In [ ]:
# official PPA comes with ffmpeg 2.8, which lacks tons of features, we use ffmpeg 4.0 here
!sudo add-apt-repository ppa:jonathonf/ffmpeg-4 # for ubuntu20.04 official PPA is already version 4.2, you may skip this step
!sudo apt-get update
!sudo apt-get install -y build-essential python3-dev python3-setuptools make cmake
!sudo apt-get install -y ffmpeg libavcodec-dev libavfilter-dev libavformat-dev libavutil-dev
# note: make sure you have cmake 3.8 or later, you can install from cmake official website if it's too old

In [ ]:
!sudo apt-get update
!sudo apt-get install -y build-essential cmake make pkg-config python3-dev python3-setuptools \
    ffmpeg libavcodec-dev libavformat-dev libavutil-dev libavfilter-dev

Hit:1 https://cli.github.com/packages stable InRelease
Hit:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:4 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:5 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:8 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading packag

In [ ]:
%cd ..

/content


In [ ]:
!git clone --recursive https://github.com/dmlc/decord

In [ ]:
%cd decord
!mkdir build
%cd build

In [ ]:
!sudo apt-get install -y libnvidia-decode-550

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libbz2-dev libpkgconf3 libreadline-dev
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  libnvidia-compute-550
The following NEW packages will be installed:
  libnvidia-compute-550 libnvidia-decode-550
0 upgraded, 2 newly installed, 0 to remove and 37 not upgraded.
Need to get 51.2 MB of archives.
After this operation, 236 MB of additional disk space will be used.
Get:1 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  libnvidia-compute-550 550.163.01-0ubuntu1 [49.5 MB]
Get:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  libnvidia-decode-550 550.163.01-0ubuntu1 [1,787 kB]
Fetched 51.2 MB in 2s (25.0 MB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so t

In [ ]:
!cmake .. -DUSE_CUDA=ON -DCMAKE_BUILD_TYPE=Release
!make

CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.


-- Checking for module 'libavdevice'
--   No package 'libavdevice' found
-- Unable to find libavdevice, device input API will not work!
-- Found FFMPEG or Libav: /usr/lib/x86_64-linux-gnu/libavformat.so;/usr/lib/x86_64-linux-gnu/libavfilter.so;/usr/lib/x86_64-linux-gnu/libavcodec.so;/usr/lib/x86_64-linux-gnu/libavutil.so;/usr/lib/x86_64-linux-gnu/libswresample.so, /usr/include/x86_64-linux-gnu
FFMPEG_INCLUDE_DIR = /usr/include/x86_64-linux-gnu 
FFMPEG_LIBRARIES = /usr/lib/x86_64-linux-gnu/libavformat.so;/usr/lib/x86_64-linux-gnu/libavfilter.so;/usr/lib/x86_64-linux-gnu/libavcodec.so;/usr/lib/x86_64-linux-gnu/libavutil.so;/

In [ ]:
!pwd

/content/decord/build/build


In [ ]:
%cd ../python
# option 1: add python path to $PYTHONPATH, you will need to install numpy separately
# !pwd=$PWD
# !echo "PYTHONPATH=$PYTHONPATH:$pwd" >> ~/.bashrc
# !source ~/.bashrc
# option 2: install with setuptools
!python3 setup.py install --user

[Errno 2] No such file or directory: '../python'
/content/decord/build/build
python3: can't open file '/content/decord/build/build/setup.py': [Errno 2] No such file or directory


 Sample Expected output:
 Vision x Text:
 tensor([[9.9761e-01, 2.3694e-03, 1.8612e-05],
         [3.3836e-05, 9.9994e-01, 2.4118e-05],
         [4.7997e-05, 1.3496e-02, 9.8646e-01]])

 Audio x Text:
 tensor([[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]])

 Vision x Audio:
 tensor([[0.8070, 0.1088, 0.0842],
         [0.1036, 0.7884, 0.1079],
         [0.0018, 0.0022, 0.9960]])

In [ ]:
import os
from PIL import Image
from IPython.display import display

def display_images_in_directory(directory):
  """Displays all image files in a given directory."""
  for filename in os.listdir(directory):
    if filename.lower().endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp')):
      try:
        img_path = os.path.join(directory, filename)
        img = Image.open(img_path)
        print(f"Displaying: {filename}")
        display(img)
      except Exception as e:
        print(f"Could not display {filename}: {e}")

# Replace 'your_directory_path' with the actual path to your directory
display_images_in_directory('./.assets') # Replace '.' with the path to your directory

In [ ]:
!ls